### ISSUE TITLE
It's working great!

### ISSUE THREAD

**Issue by donmega** [Rambalac/ACDDokanNet#1]
Just to let you know that it's working great :). Can't wait for future updates!

Made some promo for you: https://www.reddit.com/r/DataHoarder/comments/3zvc1w/there_is_a_new_and_free_way_to_mount_your_amazon/

**Comment by Liryna** [comment]
:+1:

**Comment by Rambalac** [comment]
@Liryna Do you need any special mention of Dokan other than now?

**Comment by Liryna** [comment]
I was more going to propose to put your project the Dokan website :smiley:
