### ISSUE TITLE
Can't delete cache

### ISSUE THREAD

**Issue by donmega** [Rambalac/ACDDokanNet#12]
When i try to delete cache i get the following error in the event viewer:
CachePath: Can not delete old cache: C:\Users\Administrator\AppData\Local\Temp\2\ACDDokanNetCache\SmallFiles

D:\dev2\amazon-clouddrive-dokan\amazon-clouddrive-dokan\SmallFilesCache.cs: 83

**Comment by Rambalac** [comment]
It will be released in versions after 1.6.1
