### ISSUE TITLE
Cannot Mount - "Value cannot be null" Error

### ISSUE THREAD

**Issue by rcproam** [Rambalac/ACDDokanNet#14]
This project is a great idea! Unfortunately for me the mount button only generates an error :-\

On my Windows 7 SP1 x64 Ultimate with .NET Framework 4.6.1 I did a fresh install of Dokany 0.8.0 and ACDDokanNet 1.5.2.23976
Selecting any available drive letter and clicking the "Mount" button only results in generating the following error message:

Value cannot be null.
Parameter name: uriPrefix

http://imgur.com/9M1IXH6

Result is the same when I choose "Run as administrator" for the ACD.DokanNet Settings.

I have attached the exported log file, however the error does not seem to appear in the log.

Any ideas on how to resolve this issue?

[ACDDokanNetLog.zip](https://github.com/Rambalac/ACDDokanNet/files/165008/ACDDokanNetLog.zip)

**Comment by Rambalac** [comment]
Fortunately it's not related to dokany. I think I can push update tomorrow.

**Comment by rcproam** [comment]
Awesome thanks for the prompt response Rambalac! :-)

I will look for the update and test again tomorrow.

**Comment by rcproam** [comment]
I forgot to mention, after clicking the "Mount" button ACDDokanNet also failed to launch the default web browser (I am assuming this was the intention) to authenticate to Amazon Cloud Drive.

I also tried switching my default web browser from Firefox 44 to IE 11 but this had no effect and resulted in ACDDokanNet generating the same "Value cannot be null. Parameter name: uriPrefix" Error.

**Comment by Rambalac** [comment]
Yes, my bad. I forgot to test fresh install. I pushed new release 1.5.3
https://github.com/Rambalac/ACDDokanNet/releases/tag/1.5.3
Please confirm if it's working
