### ISSUE TITLE
Feature request: Automatic update

### ISSUE THREAD

**Issue by donmega** [Rambalac/ACDDokanNet#18]
Hi!

First of all: I think ACDDokanNet is the bomb! I love it!

I have a feature request. Would it be possible to add some kind of Auto-Update feature? :100: 

Keep up the good work!

**Comment by Rambalac** [comment]
Definitely it's not impossible. Problem is how to implement it without any annoyance.

Also, I'm thinking to rename app to ClodHold. It's not released yet, but it's possible to add multiple clouds and not only Amazon.

**Comment by Rambalac** [comment]
Automatic update check is added but because I cannot find any way to make install silent you should run it manually. Problem is in Shell extension which requires Explorer restart.
