### ISSUE TITLE
Streaming video from ACD

### ISSUE THREAD

**Issue by donmega** [Rambalac/ACDDokanNet#2]
Me again :)

If you need any help with streaming video from ACD: Someone made an add-on for KODI, and it does stream videos from ACD:

https://github.com/ddurdle/Amazon-Cloud-Drive-for-KODI

**Comment by Rambalac** [comment]
Sorry, but I'm not going to implement it as XBMC. This is virtual drive, all files has to be represented as is, not reencoded. If you want you can use any XBMC-like soft to stream from virtual drive.
