### ISSUE TITLE
Prime Unlimited Photos

### ISSUE THREAD

**Issue by TMDaines** [Rambalac/ACDDokanNet#20]
Hi,

Even though Amazon Prime gives you unlimited photo storage, this app is only showing the drive as having a capacity of 5GB and will not allow me to attempt to upload more photos once capacity has reached 5GB. I can't be the only Prime user wanting to use this app, surely?

When I log into ACD through the browser, it is confirmed that the photos uploaded so far are not contributing to the storage limit, so this seems to be a problem with the app specifying a 5GB limit on the size of the drive.

**Comment by Rambalac** [comment]
I can try to report 100Tb as for unlimited.

**Comment by TMDaines** [comment]
That should work, provided I stick to uploading photos.

**Comment by Rambalac** [comment]
Problem is I can not test it because I already have Unlimited Everything and cannot register another email for Photos Unlimited with the same credit card even just for free trial.

**Comment by TMDaines** [comment]
If you compile for me, i can test it and see if it works.

**Comment by Rambalac** [comment]
Ok, try https://github.com/Rambalac/ACDDokanNet/releases/tag/1.5.6

**Comment by TMDaines** [comment]
I've used this to up all my photos and it works brilliantly. I may need to test what happens if I accidentally try and upload more than 5GB of non-photos though.

**Comment by suvichak** [comment]
Hello I still have this issue 
![image](https://cloud.githubusercontent.com/assets/9943181/18050882/755f169e-6e1b-11e6-9452-90a0f9e69a0c.png)

I am not sure why this can happened. 

I try on Both Unlimit photo + unlimit everything (Both trial) account but non of them seem to work. 

BTW, i am not amazon prime users.

**Comment by Rambalac** [comment]
I think I found the bug, strange it did not fail before. version 1.6.1 should work
