### ISSUE TITLE
Impossible to write

### ISSUE THREAD

**Issue by jhdscript** [Rambalac/ACDDokanNet#21]
Hello, I m trying to use your ACDDokanNet but I Have some issues:
* Download folder to my computer works
* Upload file Don t work. It say me I haven't permission to write (Windows Message)

Can you help me ? (I m starting the program as an administrator)

Regards

**Comment by Rambalac** [comment]
Are you uploading just in Windows Explorer or other application?

**Comment by jhdscript** [comment]
Only using windows explorer. Mount works great but I Haven t rights to write :/

**Comment by jhdscript** [comment]
Issue is fixed. The cache folder was set to read only !!!
