### ISSUE TITLE
Amazon app secrets - where?

### ISSUE THREAD

**Issue by js69** [Rambalac/ACDDokanNet#24]
Build.md mentions:

"To connect to Amazon CLoud Drive you need to register your application and get app secret keys.
Create AmazonSecret.cs in ACD.DokanNet.Gui project and replace values with your app secrets "

How would we retrieve the app secret?

**Comment by Rambalac** [comment]
In https://developer.amazon.com/iba-sp/overview.html
You need to create account, create security profile and whitelist it in https://developer.amazon.com/cd/sp/overview.html
