### ISSUE TITLE
[QUESTION] Do this client resume upload/download?

### ISSUE THREAD

**Issue by lsching17** [Rambalac/ACDDokanNet#26]
i have folders of large movie files want to backup

Does this client handle resume upload/download? (e.g. network timeout, disconnect, PC shutdown/restart)

**Comment by Rambalac** [comment]
Current public Amazon Cloud Drive does not support resuming. There is announce about new API but it's accessible through invitation, I sent a request but still no response. I hope new API has improved upload and other aspects.

**Comment by lsching17** [comment]
Then does this client handle RETRY upload/download automatically? (e.g. network timeout, disconnect, PC shutdown/restart)

**Comment by Rambalac** [comment]
It does retry, but unfortunately for really big files I get error each time.

**Comment by Rambalac** [comment]
I'm a bit disappointed in Amazon to continue developing, I still have hope in new API though.

**Comment by lsching17** [comment]
what is the retry count limit and network timeout for download/upload?

**Comment by Rambalac** [comment]
Timeout is default, I believe it's about 60 seconds. Retries are infinit in the loop where failed uploads get moved to the end of queue.

**Comment by lsching17** [comment]
Do download has default timeout and retry indefinitely?

**Comment by Rambalac** [comment]
Download has 30 sec timeout, but no retry because it can take another 30 sec. I tried internal retry and it's not the best experience when explorer lags instead of clear error.

**Comment by Rambalac** [comment]
In new version 1.6.1 you can see better what and how files get uploaded.
