### ISSUE TITLE
Cache not cleaned

### ISSUE THREAD

**Issue by Kaos1337** [Rambalac/ACDDokanNet#28]
Hi,
I'm using ACDDokanNet 1.5.5 and there is an issue with the cache: it isn't cleaned after the upload of a file, it remains there forever. http://i.imgur.com/N5J2hKA.png, another example http://i.imgur.com/4TihjgA.png
Regards.

**Comment by swvajanyatek** [comment]
i'm seeing the same.

**Comment by Rambalac** [comment]
Yes, that's my bad. But I'm too lazy to fix it in that version because it's stuck now in the middle to the next version.

**Comment by Rambalac** [comment]
It's possible I fixed your problem in 1.6.1. But old files will be deleted on next read, not exactly just uploaded but old first. After upload file get moved to read cache as it possibly can be reopened for reading by Explorer for example.

**Comment by Kaos1337** [comment]
Seems working fine (the v1.6.1 after some days of testing), thanks.
