### ISSUE TITLE
The remote server returned an error: (400) Bad Request

### ISSUE THREAD

**Issue by thetorx** [Rambalac/ACDDokanNet#29]
Hi, i'm using version 1.5.5.36843 on windows 10.
Since this afternoon when I push the mount button and the message "Please follow Amazon Cloud Drive login page in your browser and retrun here after it's complete" appears, I get another window with the message "The remote server returned an error: (400) Bad Request".
Thanks for your help

**Comment by elitegoodguy** [comment]
I'm getting the same issue on the exact same version/Windows version

**Comment by Rambalac** [comment]
Yep, Amazon is messing with API. It's not public anymore.

**Comment by thetorx** [comment]
oh crap... so it's not working for anyone.
any way to solve? expandrive still works

**Comment by feutl** [comment]
it was working for me a few days ago, on windows 10

**Comment by aadam101** [comment]
Can anyone confirm if this works anymore?  When click the mount button a browser page opens that contains the word "start" but nothing else happens.

**Comment by thetorx** [comment]
it does not work for me, but no browser page opens, i just have the error i wrote in my first post

**Comment by JMSDOnline** [comment]
@aadam101, I had that same issue. I looked at the headers and realized it was an adblocker extension blocking the connect screen.

**Comment by Rambalac** [comment]
I dont see now any issues with signing in. I prereleased new version, but there is nothing changed in Amazon signing in.  Do you still have problem with it?

**Comment by RonnieBlaze** [comment]
Login page never comes up when trying to add cloud.
Running DokanSetup-1.0.0.5000 with Prerelease v1.6.1

Opens browser to a page that says "start"

**Comment by Rambalac** [comment]
What do you get if you open this url in browser?
```
https://www.amazon.com/ap/oa?client_id=amzn1.application-oa2-client.ce45fa54a8ec4daeb7f082343fa1e8d8&scope=clouddrive:read_all%20clouddrive:write&response_type=code&redirect_uri=http://localhost:45674/signin/
```

**Comment by RonnieBlaze** [comment]
Rambalac, 
When i clicked on mount and it opened the tab to the "start" i pasted the url you gave above, and it brought up the sign in page, and let me sign in. The drive is now mounted!

My default browser is firefox 49.0.1. I i went as far as making a new black profile and trying it with the same out come, Also tried chrome and IE 11.

But it is mapped now, and since the app is auth'd i dont think i will have a problem remounting it.

Thank you for the quick help

**Comment by Rambalac** [comment]
But that's not a solution. I have no idea where it even take that text "start". If you cold attach log it could help.

**Comment by JMSDOnline** [comment]
> But that's not a solution. I have no idea where it even take that text "start". If you cold attach log it could help.

It happened for me when I attempted to mount/signin. It showed up in the browser window (Currrent Chrome build). It was due to an AdBlock extension in Chrome blocking the sign-in... this was in my instance. Disabling the adblock extension momentarily brought me to the sign-in page successfully.

**Comment by Rambalac** [comment]
@JMSDOnline, but @RonnieBlaze tried different browsers and I bet he did not have Adblock in all of them.

**Comment by JMSDOnline** [comment]
Cool, just sharing my experience in the off chance that others encounter the same thing and have an AdBlock extension. 

**Post Script:**
I have AdBlocker extensions in ever browser I use

**Comment by RonnieBlaze** [comment]
@Rambalac Correct, i did disable adblocker in my Firefox, but when i made the new profile there were no addons and it did the same thing. I also tried on 2 computers all did the same thing.

**Comment by RonnieBlaze** [comment]
any idea why the app was using 3gigs of ram at idle?

**Comment by Rambalac** [comment]
I could not make it to use more than 50-60 Mbytes. When does that happen?

**Comment by RonnieBlaze** [comment]
@Rambalac 
nothing, computer just idles with the drive mounted. 
now i do have almost 1TB of files on my amazon cloud. i dont know if that matters or not

**Comment by aadam101** [comment]
I have over 1TB and mine never uses over 120MB.

**Comment by RonnieBlaze** [comment]
Interesting.. what version do you have installed?
I am using
ACDDokanNetInstaller161
DokanSetup-1.0.0.5000

**Comment by aadam101** [comment]
Version 1.6.1

**Comment by Rambalac** [comment]
There is version 1.6.2, but it should not change anything. In my case it can jump to 150Mb, but when I check after few hours it returns back to 50Mb. Difference can be if you have some software crawling disk constantly.
And I would recommend to install Dokan 1.0.1 because 1.0.0 has deadlock problem.

**Comment by aadam101** [comment]
I upgraded to 1.6.2 today. I've been watching the ram for the last half
hour while I am uploading files and it has been around 35mb the entire time.

**Comment by RonnieBlaze** [comment]
I will upgrade both, and look into the disk activity and see how it goes.

**Comment by RonnieBlaze** [comment]
Ok, my problem is definitely anti-virus related.
when i disabled my Kaspersky Endpoint Security 10 the process has 0% cpu usage and minimal ram usage.

I tried excluding the mounted drive but that didn't seem to stop it from accessing the drive.  
I will continue messing with the settings to see if i can figure out whats causing it.
