### ISSUE TITLE
How to use this for noobs ?

### ISSUE THREAD

**Issue by arfaatc** [Rambalac/ACDDokanNet#30]
Hey, I am so sorry i dont know i should post it or not but i really need help i want to set this up but i am a complete noob in developing world please can u help me step by step how to use it please ?
I am having WINDOWS 10

**Comment by arfaatc** [comment]
PLEASE HELP ME HOW DO I USE THIS IN WINDOWS 10 PLEASE HELP ME USE STEP BY STEP PELASE

**Comment by Rambalac** [comment]
What exactly is not clear in step by step installation manual?
