### ISSUE TITLE
Does not install on Windows 2012 R2

### ISSUE THREAD

**Issue by wickedsun** [Rambalac/ACDDokanNet#32]
The installer complains that Dokan needs to be installed, even if it already is.

Any way you can look into this?

**Comment by feutl** [comment]
have you verified that the correct version is installed. the latest version from the dokan website is not working you have to install the version mentioned in the documentation.

**Comment by wickedsun** [comment]
Ah, that would make sense, although some of the doc says to get the latest (install guide) while further down it mentions 0.8.0.

I wasn't sure which one to follow or which one had been updated and the other not, so I went with 1.0.

**Comment by Rambalac** [comment]
New version works with Dokany 1.0.0 and installer has better instructions. Should this ticket be closed?

**Comment by wickedsun** [comment]
You can go ahead and close it, thank you!

---
Charles D’Aoust
