### ISSUE TITLE
The error code is 2835. This User level driver requires kernal driver Dokan. Please download and install DokanInstall_X.X.X_redist.exe.

### ISSUE THREAD

**Issue by ZeddicusZedd** [Rambalac/ACDDokanNet#33]
I have installed DokanSetup_redist-1.0.0.5000.exe but I'm getting error 2835 when installing ACDDokanNetInstaller.  I have disabled my antivirus and reboot my computer.  Please see the attached log.

Thank you for your help and creating a much needed program!
Regards,
Zedd

[ACDDokanNetInstaller.txt](https://github.com/Rambalac/ACDDokanNet/files/515357/ACDDokanNetInstaller.txt)

**Comment by Rambalac** [comment]
As readme says current version supports only Dokany 0.8.0.
