### ISSUE TITLE
BSOD - 1.6.1

### ISSUE THREAD

**Issue by itzeddie** [Rambalac/ACDDokanNet#34]
Hi,

I am running Windows 10 build 14951 and when trying to map ACD using 1.6.1 and Dokany 1.0.5000 I get an immediate BSOD once I have entered my credentials on the ACD website.

Please advise what events if any you would like.

Thanks,
Ed

**Comment by itzeddie** [comment]
Thanks for the response Rambalac, one further issue is I can't get the GUI to open, unsure if its being caused by this...

Application_Startup: Starting Version 1.6.1.7157

H:\Projects\C#\ACDDokanNet\ACD.DokanNet.Gui\App.xaml.cs: 389

After that I get a number of errors including;

Application: ACD.DokanNet.Gui.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.

**Comment by Rambalac** [comment]
Well, that's... "better". I will check when get back home.

**Comment by Rambalac** [comment]
That's strange. Probably BSOD corrupted settings file. As for now you can try to delete all folders from %USERPROFILE%\AppData\Local\Rambalac

**Comment by Liryna** [comment]
@Rambalac I promise a 1.0.1 for this week ❤️

**Comment by Rambalac** [comment]
@Liryna Thank you a lot.
By the way, what happens with dokany and caller app if say FindFiles processor get delayed? Is it using timeout defined in Mount?

**Comment by Liryna** [comment]
You mean by using TryResetTimeout of DokanInfo ? It will extend be extended by the time requested in prams that has to be less than https://github.com/dokan-dev/dokany/blob/047c2b6d0bf96043f958d6b24a40ba69eab7034b/sys/dokan.h#L95

**Comment by Rambalac** [comment]
No, I mean does that timeout works for FindFiles? Because sometime when it's browsing folder with images and Explorer is trying to read all of them for thumbnails all operations can slowdown because of Amazon servers timeout including check for folders content.

**Comment by Liryna** [comment]
Yes, the timeout also apply to FindFiles.

**Comment by Liryna** [comment]
@Rambalac https://github.com/dokan-dev/dokany/releases/tag/v1.0.1 👍

**Comment by Rambalac** [comment]
@Liryna Yes, I noticed and testing now. Thank you very much.

**Comment by Rambalac** [comment]
@itzeddie Can you try Dokany 1.0.1 and my version 1.6.2?

**Comment by Rambalac** [comment]
@itzeddie Do you have any updated? Have you tried 1.6.3?
