### ISSUE TITLE
No audio when playing video

### ISSUE THREAD

**Issue by Conroman16** [Rambalac/ACDDokanNet#36]
Hey there.  I've got the most recent release of ACDDokanNet installed on Windows Server 2012 R2 with Dokany 1.0.1.  Everything seems to be working well, with the exception of playing video.  

When I start a video, the video plays fine, no issues whatsoever, but there is no audio.  The video player detects the audio track correctly and believes that it's actually playing the audio, but there is no audio that comes through.  Then if I copy that exact same file from the virtual drive to somewhere local (say, my Desktop) and play it, the audio plays fine.

I first noticed the problem when attempting to play a video from Plex, however I've since realized it's not just limited to Plex and actually is an issue in VLC as well.

Is this a known issue by chance?  I have found no other posts online regarding this issue, so I'm at a loss as to where to go from here.  Are there any troubleshooting steps I can take to assist in identifying/resolving the issue?  I've exported the logs and have found that there are no errors or any other events generated when the audio fails to play, so I'm not including it with this issue submission.

Thank you!

**Comment by etomm** [comment]
If I don't remember wrong Windows Server should not have the audio service
started automatically on boot.

**Comment by Conroman16** [comment]
Wow, you learn something new every day.  That was the fix.  I've been managing Windows machines for quite a while but I had no knowledge of the windows audio service at all.  I started it up and the audio worked like a charm.  Sorry to make an unnecessary issue.  Thanks a ton!

**Comment by Rambalac** [comment]
Since when video works fine o_O

**Comment by Conroman16** [comment]
The video played fine, it just didn't have audio.  Starting the audio service fixed it though.  I was a bit surprised that I had to enable the audio service because local plex videos play fine without it, but it's working now so I'm not complaining haha
