### ISSUE TITLE
Should copy/paste work from within the  drive?

### ISSUE THREAD

**Issue by sigwx** [Rambalac/ACDDokanNet#37]
Trying to move a folder with copy/paste (then delete the original if it works) and it creates the folder, looks to be moving the data (watching the win10 progress bar anyway) but then states "You'll need to provide administrator permission to copy to this folder", which I select Continue, but then it repeatedly says "You need permission to perform this action".  Watching the Settings tool, I don't see the 'Transferring' values changing, so maybe its not actually moving the files?   I wasn't sure if this was an install/setup issue or some other known limitation.  
Thanks!

**Comment by Rambalac** [comment]
Generally copy should work.
What app and dokany version?
I would recommend Upload here, it does not need to assemble files in temp folder before upload.

**Comment by Rambalac** [comment]
Within drive copy has to download file before upload. While move is atomic done by cloud service itself. Move within drive is 100% reliable unlike copy. In worst scenario Amazon will place your folder and files into trash, my app is unable to delete files completely.

**Comment by sigwx** [comment]
So, just installed, so 1.6.2.23397 for the ACD, the Dokan Library is 1.0.1.1000 Bundle.

I figured the drive copy would need to download and then upload, but the ACD isn't showing Transfer going on.  If the files are already on Amazon, what would I be 'Uploading', or do I need to download a copy first?  I tried just selecting the files, the Copy from the Explorer, then 'Upload here' and the ACD showed an attempt to upload files but flagged them all as not existing.

Thanks!

**Comment by Rambalac** [comment]
I fixed few things to make downloading more reliable in v1.6.3. I hope it can help.

**Comment by GoWithitRoger** [comment]
"I would recommend Upload here,..."

Is that an app name or feature of AcDDokan?

**Comment by Rambalac** [comment]
It's feature of this app. But actually it did not work well before today's update.
It's context menu item in Windows Explorer. Instead of **Paste** in cloud drive folder select **Upload Here**

**Comment by GoWithitRoger** [comment]
Thanks for the explanation. And THANK YOU FOR THIS AWESOME TOOL!
