### ISSUE TITLE
Program crash while deleting Microsoft OneDrive

### ISSUE THREAD

**Issue by hakkai2015** [Rambalac/ACDDokanNet#38]
I create an Microsoft OneDrive by mistake and try to delete it from list, but when I press Delete button, program crashes. So I can't delete this record. 
Screenshot and system journal in attachment.

[DOKAN.zip](https://github.com/Rambalac/ACDDokanNet/files/610036/DOKAN.zip)

**Comment by Rambalac** [comment]
I uploaded v1.6.3. Could you try it? It should if not stop failing but at least delete it. Not sure what's wrong there I added more logging.

**Comment by hakkai2015** [comment]
I just updated to v 1.6.3 and now I can delete unwanted OneDrive accounts. Thanks.
