### ISSUE TITLE
Cannot mount after restart

### ISSUE THREAD

**Issue by yk64** [Rambalac/ACDDokanNet#4]
After restarting the OS, I cannot mount ACD again. When I click the mount button, a dialog that says "Please follow Amazon Cloud Drive login page in your browser and return here after it's complete" and the app crashes immediately. I tried removing the cache directory and restarting the app but no help.

Environment:
Latest ACD.DokanNet (1.4)
Windows 8.1 Home Edition
Accessing PC directly (Not through remote desktop)

The following is in the event viewer:

System.InvalidOperationException
   Location System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   Location System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   Location Azi.ACDDokanNet.Gui.App+<Mount>d__43.MoveNext()
   Location System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   Location System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   Location Azi.ACDDokanNet.Gui.ViewModel+<Mount>d__18.MoveNext()
   Location System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   Location System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   Location Azi.ACDDokanNet.Gui.MainWindow+<mountButton_Click>d__3.MoveNext()
   Location System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   Location System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   Location System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   Location System.Windows.Threading.DispatcherOperation.InvokeImpl()
   Location System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   Location System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   Location System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   Location System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   Location System.Windows.Threading.DispatcherOperation.Invoke()
   Location System.Windows.Threading.Dispatcher.ProcessQueue()
   Location System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   Location MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   Location MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   Location System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   Location System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   Location System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   Location MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   Location MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   Location System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   Location System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   Location System.Windows.Application.RunDispatcher(System.Object)
   Location System.Windows.Application.RunInternal(System.Windows.Window)
   Location System.Windows.Application.Run(System.Windows.Window)
   Location Azi.ACDDokanNet.Gui.App.Main()

**Comment by Rambalac** [comment]
Could you try new 1.4.1?
Also if it still happen after restart, can you check before starting settings and mounting again if ACDDokanNet.exe is already started?
Automount on restart should work now also.

**Comment by yk64** [comment]
Thank you for the response.
I tried the latest version (1.4.1.41075) but the app still crashes. Before I start the app, I checked the task manager and confirmed that there is no ACDDokanNet.exe running. I found that simply trying to export log makes the app crash, right after I click on the OK button in the save dialog. I hope this helps you fix the issue...

**Comment by Rambalac** [comment]
I added new version 1.4.2 that should not crash and show some error message, though does not guaranty mounting.
Log export should be done after Run as Administrator

Also, I tried to install it on different PC without developer software. One of reasons for mounting fail could be dokany. It should be 0.8.0 to work. Before and after there are too many changes to work together.

**Comment by yk64** [comment]
I tried 1.4.2. I ran it as Administrator. I could export logs successfully however mounting still fails saying "Can't install the Dokan driver". Dokan 0.8.0 has been installed successfully, as ACDDokanNet had been working correctly before.

Here is the log

Mount: DokanNet.DokanException: Can't install the Dokan driver
   Location DokanNet.Dokan.Mount(IDokanOperations operations, String mountPoint, DokanOptions mountOptions, Int32 threadCount, Int32 version, TimeSpan timeout)
   Location Azi.ACDDokanNet.VirtualDriveWrapper.Mount(String path, Boolean readOnly)

D:\dev2\amazon-clouddrive-dokan\amazon-clouddrive-dokan\VirtualDriveWrapper.cs: 57



Another one. (The fact is, no drive other than C: exists in my PC.)
Mount: Drive letter Z is already used

D:\dev2\amazon-clouddrive-dokan\ACD.DokanNet.Gui\App.xaml.cs: 318


Mount: Drive letter Y is already used

D:\dev2\amazon-clouddrive-dokan\ACD.DokanNet.Gui\App.xaml.cs: 318

.. and same for X, W and so on

**Comment by Rambalac** [comment]
Cannot find letter means dokany does not want to mount drive for some reason. It does not say exactly why just fail, I decided used letter is most obvious reason.
I wish to help you but that  involves more complicated things to check. I have reported few issues in dokany myself. Do you still have hope in my app? I have small test app which will print more verbose logs.

**Comment by yk64** [comment]
I'm still hoping that this works correctly. Many people seem to be looking for this kind of app.
ref: https://www.amazon.com/gp/help/customer/forums/ref=cs_hc_g_tv?ie=UTF8&forumID=Fx1SKFFP8U1B6N5&cdThread=Tx3EB5KJH3175PF

I can run the test app if you need.

**Comment by Rambalac** [comment]
Do you still have that issue? Dokany updated to 1.0.0 and I just updated my app to use it.
