### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by habano** [Rambalac/ACDDokanNet#41]
I have ACD set up and I can view my files in a mounted drive, however when I try to transfer a file I get a Destination Folder Access Denied message. This happens even with files as small as 1 KB. Windows asks me to provide administrator permission, but it makes no difference; I can't transfer any files. Everything seems to be set up for read only even though I did not check the read only box in options. I have my cache set to %TEMP%\ACDDokanNetCache, small files size set to 20 Mb and small files cache set to 1000 Mb. Any idea what the problem could be?

**Comment by habano** [comment]
I noticed a closed issue that says the cache folder permissions may cause this issue. Unfortunately, if I try to change the cache folder, the program crashes. If I click on Export Log the program also crashes.
I tried changing the permissions on the %TEMP%\ACDDokanNetCache folder, but I still get  access denied messages.
FYI, I'm running Windows 10 Pro and the latest version of ACD Dokan.Net

**Comment by Rambalac** [comment]
If you are transferring files to ACD I would recommend using Copy and Upload here from Explorer context menu instead of Paste.

**Comment by habano** [comment]
I completely uninstalled ACD Dokan.Net, including the configuration files. After reinstalling, I can now change the cache directory without the program crashing.
I still cannot transfer files to my ACD folders. Copy/Paste results in folder access messages. Copy/Upload gives me a message saying Cached Upload File Is Not Found

**Comment by habano** [comment]
Here is my log in case it helps you to determine what might be happening.
[ACDDokanNetLog.zip](https://github.com/Rambalac/ACDDokanNet/files/622324/ACDDokanNetLog.zip)

**Comment by Rambalac** [comment]
Can you try 1.6.4?

**Comment by habano** [comment]
I've tried 1.6.4 as well as various other programs for accessing my ACD files. Unfortunately nothing seems to work, so the problem must be on my end. Thanks for your help.
