### ISSUE TITLE
File Already Exists 

### ISSUE THREAD

**Issue by joemarshalljm** [Rambalac/ACDDokanNet#44]
Anyway to replace files when you get a 'File Already Exists' message? I'd rather re-upload sometimes

**Comment by Rambalac** [comment]
File Already Exists often happens when the first time Amazon did not report correctly about upload result. But if the file got uploaded It should be absolutely fine.
And if you overwrite file existed before copy started it should overwrite properly.

**Comment by aadam101** [comment]
I get this message a lot but the file does upload anyway. Just ignore the
message.

**Comment by Rambalac** [comment]
@aadam101 For big files Amazon does not report properly upload result and returns some http error like 503 and no file in the folder. But when file get reuploaded Amazon returns error about conflict. So I wait for some time and check if file appeared in the folder, if still nothing I reupload and if conflict it shows File Already Exists. But it will be the same File Already Exists if you upload some file with the same name in the same folder other way, so I don't hide such errors.

**Comment by aadam101** [comment]
Thank you for the explanation. It hasn't been a problem since the file does
upload despite the message.
