### ISSUE TITLE
App key

### ISSUE THREAD

**Issue by sollidius** [Rambalac/ACDDokanNet#55]
Hey,

I installed ACDDokanNet on my computers and on a USB drive.
However, I lost the USB drive a couple days ago, and I'm worried about my data.
When logging in to the ACD manager, acddokan is only listed once as authorized app, even tho this was installed on multiple devices.
I revoked the access and re-authenticated on my computer. 
Now my question is: will the access via the USB drive be disabled now? Will it need to re-auth as well? Or is the oauth key on the USB drive still valid?

Thanks

**Comment by Rambalac** [comment]
OAuth token is kept in app settings file in user AppData folder.

**Comment by sollidius** [comment]
Even when installed on a USB drive? So i should not worry that there is unauthorized access to my ACD?

**Comment by Rambalac** [comment]
It cannot be installed on USB drive because it requires Dokan driver which cannot be just copied. It's WPF application and if you don't do anything special it will save settings in Users folder.
