### ISSUE TITLE
can't access file with zero size

### ISSUE THREAD

**Issue by D4nielB** [Rambalac/ACDDokanNet#57]
Just tried to access a file with a size of zero (backup of my Synology NAS), and ACDDokanNet throws an error.

OS: Win 10 x64, current versions of Dokany and ACDDokanNet

**Comment by D4nielB** [comment]
Creating a zero size test file (test.txt) on my pc and copying it to AC works, but trying to access it gives an error message too. Deleting works though...

**Comment by Rambalac** [comment]
Amazon does not support 0 length files, so I create them virtually to prevent some errors.

**Comment by D4nielB** [comment]
Finally had the time to test a bit.

Installed trial versions of NetDrive2 and ExpanDrive. With both I was able to create a zero length file on Amazon Drive and open it. With ACDN this is not possible: creating and deleting works, but trying to open the file with a text editor or other tools doesn't work.

Any logs I can provide?

**Comment by Rambalac** [comment]
Seems I fixed problem with uploading and downloading zero length file. Next release will have fix.

**Comment by D4nielB** [comment]
Great news! Will test it once new version is released!

**Comment by Rambalac** [comment]
Released in 1.7.0

**Comment by D4nielB** [comment]
Works now, thanks for the fix
