### ISSUE TITLE
Readme has links to Dokan 0.8.0 but says 1.0.0

### ISSUE THREAD

**Issue by Rondom** [Rambalac/ACDDokanNet#65]
Hi,
the readme has a link to 0.8.0. 

       * [Dokany 1.0.0](https://github.com/dokan-dev/dokany/releases/tag/v0.8.0) is required.

Maybe link to 1.0.0 or any later 1.x.y version such as 1.0.3 ([ABI is stable within major version](https://github.com/dokan-dev/dokany/wiki/How-to-package-your-application-with-Dokan#dokan-versioning))

**Comment by Rambalac** [comment]
Sorry, my bad.
I will test it with 1.0.3, but 1.0.1 works for sure.

**Comment by Rambalac** [comment]
Fixed. 1.0.3 look ok.
