### ISSUE TITLE
Error when copy a file

### ISSUE THREAD

**Issue by nguyendotuong** [Rambalac/ACDDokanNet#68]
Hi Rambalac,

After mounting, I tried to copy a file from my local folder to the new mounted disk drive. An error occurred as you can see in the attached image.
![interupt_action](https://cloud.githubusercontent.com/assets/9045009/24905289/01728c08-1ee6-11e7-96f5-f64fff11f285.JPG)
But, when I click "Skip", the file is already copied.
Could you please take a look?

Thanks!

**Comment by Rambalac** [comment]
Just as workaround. If you copy files in explorer it's better and faster instead of normal pasting or dropping use **Upload Here** feature. For that you need to put selected files into clipboard by Ctrl+C or Copy in context menu and at the destination open context menu and select **Upload Here**.

**Comment by Rondom** [comment]
I think this is an actual issue and should not be closed. It looks like a wrong error code is returned. Maybe someone can post logs and maybe ProcessMonitor logs as well?
